[package]
name = "auth-api"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
auth-core.workspace = true
axum.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["trace", "request-id", "timeout", "cors"] }
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
chrono.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
tracing-opentelemetry.workspace = true