[package]
name = "auth-server"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
auth-core.workspace = true
auth-postgres.workspace = true
auth-api.workspace = true
auth-crypto.workspace = true
auth-telemetry.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "net"] }
axum.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
config.workspace = true
dotenvy.workspace = true
clap.workspace = true
chrono.workspace = true
secrecy.workspace = true
